### ISSUE TITLE
Version 0.2.0 not pushed to RubyGems

### ISSUE THREAD

**Issue by pusewicz** [braingourmets/currency_select#43]
Hi @braingourmets!

Thanks for an awesome gem!

It looks like [RubyGems](https://rubygems.org/gems/currency_select) has only version 0.1.5 available, would you mind pushing the newest one too?

Thanks!

**Comment by oliverklee** [comment]
I'll take care of it. It might take some time, though.

**Comment by pusewicz** [comment]
Hey @oliverklee! Can I help in any way?

**Comment by oliverklee** [comment]
Yes. A link how to publish a gem will be helpful (as it's my first time).

**Comment by pusewicz** [comment]
@oliverklee Here's the info required: http://guides.rubygems.org/publishing/

**Comment by oliverklee** [comment]
@pusewicz Thanks! I'll do my very best!

**Comment by oliverklee** [comment]
Done: https://rubygems.org/gems/currency_select
