### ISSUE TITLE
priority_currencies feature

### ISSUE THREAD

**Issue by LuisErnestoZamb** [braingourmets/currency_select#56]
There is a feature on "country_select gem" that allow **supplying priority countries to be placed at the top of the list** called priority_countries. On that case, it is receiving some parameters such as ["GB", "FR", "DE"] and those will be displayed at the begging. Why we don't have a "priority_currencies" to show those currencies which we want at the begging? I have tried another option as adding at least a value or selecting this by default, both without success. 

What I am looking for show looks like this:
`  <%= f. currency_select : currency, , priority_currencies: ["AUD", "EUR", "USD"] %>`
![2019-07-04_14-06-15_selecting_country](https://user-images.githubusercontent.com/9245605/60683317-2586fd80-9e65-11e9-9bca-e6d34eabfce9.gif)
Regards,

**Comment by oliverklee** [comment]
@LuisErnestoZamb Would you be willing to create a pull request for this?

**Comment by LuisErnestoZamb** [comment]
Ok. I did my work. Once I reviewed the spec I realized that code was on there but works differently than country_select gem. Pull request created.
