### ISSUE TITLE
"undefined method `flat_map' for "currency":String

### ISSUE THREAD

**Issue by Captain1** [braingourmets/currency_select#7]
Doesn't work for me.

**Comment by tanordheim** [comment]
I haven't touched this code in a long while, but eyeballing that piece of code right now it looks like you're passing a string into `priority_currencies` instead of an array of strings. Can you show some code if this doesn't solve your issue?

**Comment by oliverklee** [comment]
Hi @Captain1 Could you please post the your code that triggers the problem for you? Thanks!

**Comment by oliverklee** [comment]
Closing due to missing feedback. @Captain1 Please feel free to reopen this ticket with more information!

**Comment by LuisErnestoZamb** [comment]
Hi, I believe @Captain1 was looking for an option that country_select gem is having (called: "priority_countries"), on this case: priority_currencies.

**Comment by oliverklee** [comment]
If that is correct, @Captain1, please feel free to reopen the ticket with more information.

**Comment by LuisErnestoZamb** [comment]
It seems @Captain1 is on his holidays. What we should do now? I mean, there is a "feature" that allow add "Countries" at the beginning of the list, can we have some "Currencies" at the beginning? or how we could pre-select one currency by default? Should I open a new ticket or we can start from here? Regards, CC: @oliverklee

**Comment by oliverklee** [comment]
@LuisErnestoZamb Please open a separate ticket for your issue.
